platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

def all_pods
  config = use_native_modules!
  use_unimodules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
    # 这里做过修改hermes_enabled => true
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  # 友盟分享
  pod 'UMCCommon'

  pod 'UMCShare/UI'
  # pod 'UMCShare/Social/WeChat'
  pod 'UMCShare/Social/Sina'
  pod 'UMCShare/Social/Email'
  pod 'UMCShare/Social/SMS'
  pod 'JPush', :path => '../node_modules/jpush-react-native'
  pod 'JCore', :path => '../node_modules/jcore-react-native'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  use_flipper!()
end

abstract_target 'defaults' do
  # force use our own JitsiMeetSDK
  pod 'JitsiMeetSDK', :git => 'https://github.com/RocketChat/jitsi-meet-ios-sdk-releases.git'

  all_pods

  target 'RocketChatRN' # Experimental app
  target 'Rocket.Chat' # Official app
  target 'ShareRocketChatRN'
  target 'NotificationService'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
  react_native_post_install(installer)
end
